title: Mishan Phiri
logo: /images/MishPortrait.jpg
Description: "Data Proffesional, BI Analyst, Data Science and Data Engineering. 
Mishan Phiri is a data professional currently employed as a BI Analyst. Her work focuses on streamlining and automating reporting processes. She aims to become an all-rounded data professional, including expertise in Data Science and Engineering.
#show_downloads: true
theme: jekyll-theme-centrarium
#plugins: jekyll-include-cache
